<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-15T15:06:53 IST" name="Suite" finished-at="2024-10-15T15:07:08 IST" duration-ms="14343">
    <groups>
    </groups>
    <test started-at="2024-10-15T15:06:53 IST" name="Test" finished-at="2024-10-15T15:07:08 IST" duration-ms="14343">
      <class name="api.test.UserTestcase">
        <test-method is-config="true" signature="setUserPayload()[pri:0, instance:api.test.UserTestcase@3a52dba3]" started-at="2024-10-15T15:06:54 IST" name="setUserPayload" finished-at="2024-10-15T15:06:55 IST" duration-ms="1289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUserPayload -->
        <test-method signature="validateCreateUser()[pri:1, instance:api.test.UserTestcase@3a52dba3]" started-at="2024-10-15T15:06:55 IST" name="validateCreateUser" finished-at="2024-10-15T15:06:59 IST" duration-ms="4216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateUser -->
        <test-method signature="validateGetUser()[pri:2, instance:api.test.UserTestcase@3a52dba3]" started-at="2024-10-15T15:06:59 IST" name="validateGetUser" finished-at="2024-10-15T15:07:02 IST" duration-ms="2859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateGetUser -->
        <test-method signature="validateUpdateUser()[pri:3, instance:api.test.UserTestcase@3a52dba3]" started-at="2024-10-15T15:07:02 IST" name="validateUpdateUser" finished-at="2024-10-15T15:07:06 IST" duration-ms="3982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdateUser -->
        <test-method signature="validateDeleteUser()[pri:4, instance:api.test.UserTestcase@3a52dba3]" started-at="2024-10-15T15:07:06 IST" name="validateDeleteUser" finished-at="2024-10-15T15:07:08 IST" duration-ms="1439" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.test.UserTestcase.validateDeleteUser(UserTestcase.java:113)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteUser -->
      </class> <!-- api.test.UserTestcase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
